// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	foov1alpha1 "go.opendefense.cloud/kit/example/client-go/applyconfigurations/foo/v1alpha1"
	internal "go.opendefense.cloud/kit/example/client-go/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=foo.opendefense.cloud, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Bar"):
		return &foov1alpha1.BarApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("BarSpec"):
		return &foov1alpha1.BarSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterBar"):
		return &foov1alpha1.ClusterBarApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
