// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apifoov1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	versioned "go.opendefense.cloud/kit/example/client-go/clientset/versioned"
	internalinterfaces "go.opendefense.cloud/kit/example/client-go/informers/externalversions/internalinterfaces"
	foov1alpha1 "go.opendefense.cloud/kit/example/client-go/listers/foo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBarInformer provides access to a shared informer and lister for
// ClusterBars.
type ClusterBarInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() foov1alpha1.ClusterBarLister
}

type clusterBarInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterBarInformer constructs a new informer for ClusterBar type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterBarInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterBarInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterBarInformer constructs a new informer for ClusterBar type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterBarInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().ClusterBars().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().ClusterBars().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().ClusterBars().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().ClusterBars().Watch(ctx, options)
			},
		},
		&apifoov1alpha1.ClusterBar{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterBarInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterBarInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterBarInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apifoov1alpha1.ClusterBar{}, f.defaultInformer)
}

func (f *clusterBarInformer) Lister() foov1alpha1.ClusterBarLister {
	return foov1alpha1.NewClusterBarLister(f.Informer().GetIndexer())
}
