// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	foov1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	applyconfigurationsfoov1alpha1 "go.opendefense.cloud/kit/example/client-go/applyconfigurations/foo/v1alpha1"
	scheme "go.opendefense.cloud/kit/example/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BarsGetter has a method to return a BarInterface.
// A group's client should implement this interface.
type BarsGetter interface {
	Bars(namespace string) BarInterface
}

// BarInterface has methods to work with Bar resources.
type BarInterface interface {
	Create(ctx context.Context, bar *foov1alpha1.Bar, opts v1.CreateOptions) (*foov1alpha1.Bar, error)
	Update(ctx context.Context, bar *foov1alpha1.Bar, opts v1.UpdateOptions) (*foov1alpha1.Bar, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bar *foov1alpha1.Bar, opts v1.UpdateOptions) (*foov1alpha1.Bar, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*foov1alpha1.Bar, error)
	List(ctx context.Context, opts v1.ListOptions) (*foov1alpha1.BarList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *foov1alpha1.Bar, err error)
	Apply(ctx context.Context, bar *applyconfigurationsfoov1alpha1.BarApplyConfiguration, opts v1.ApplyOptions) (result *foov1alpha1.Bar, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, bar *applyconfigurationsfoov1alpha1.BarApplyConfiguration, opts v1.ApplyOptions) (result *foov1alpha1.Bar, err error)
	BarExpansion
}

// bars implements BarInterface
type bars struct {
	*gentype.ClientWithListAndApply[*foov1alpha1.Bar, *foov1alpha1.BarList, *applyconfigurationsfoov1alpha1.BarApplyConfiguration]
}

// newBars returns a Bars
func newBars(c *FooV1alpha1Client, namespace string) *bars {
	return &bars{
		gentype.NewClientWithListAndApply[*foov1alpha1.Bar, *foov1alpha1.BarList, *applyconfigurationsfoov1alpha1.BarApplyConfiguration](
			"bars",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *foov1alpha1.Bar { return &foov1alpha1.Bar{} },
			func() *foov1alpha1.BarList { return &foov1alpha1.BarList{} },
		),
	}
}
