// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	foov1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	applyconfigurationsfoov1alpha1 "go.opendefense.cloud/kit/example/client-go/applyconfigurations/foo/v1alpha1"
	scheme "go.opendefense.cloud/kit/example/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterBarsGetter has a method to return a ClusterBarInterface.
// A group's client should implement this interface.
type ClusterBarsGetter interface {
	ClusterBars() ClusterBarInterface
}

// ClusterBarInterface has methods to work with ClusterBar resources.
type ClusterBarInterface interface {
	Create(ctx context.Context, clusterBar *foov1alpha1.ClusterBar, opts v1.CreateOptions) (*foov1alpha1.ClusterBar, error)
	Update(ctx context.Context, clusterBar *foov1alpha1.ClusterBar, opts v1.UpdateOptions) (*foov1alpha1.ClusterBar, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterBar *foov1alpha1.ClusterBar, opts v1.UpdateOptions) (*foov1alpha1.ClusterBar, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*foov1alpha1.ClusterBar, error)
	List(ctx context.Context, opts v1.ListOptions) (*foov1alpha1.ClusterBarList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *foov1alpha1.ClusterBar, err error)
	Apply(ctx context.Context, clusterBar *applyconfigurationsfoov1alpha1.ClusterBarApplyConfiguration, opts v1.ApplyOptions) (result *foov1alpha1.ClusterBar, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterBar *applyconfigurationsfoov1alpha1.ClusterBarApplyConfiguration, opts v1.ApplyOptions) (result *foov1alpha1.ClusterBar, err error)
	ClusterBarExpansion
}

// clusterBars implements ClusterBarInterface
type clusterBars struct {
	*gentype.ClientWithListAndApply[*foov1alpha1.ClusterBar, *foov1alpha1.ClusterBarList, *applyconfigurationsfoov1alpha1.ClusterBarApplyConfiguration]
}

// newClusterBars returns a ClusterBars
func newClusterBars(c *FooV1alpha1Client) *clusterBars {
	return &clusterBars{
		gentype.NewClientWithListAndApply[*foov1alpha1.ClusterBar, *foov1alpha1.ClusterBarList, *applyconfigurationsfoov1alpha1.ClusterBarApplyConfiguration](
			"clusterbars",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *foov1alpha1.ClusterBar { return &foov1alpha1.ClusterBar{} },
			func() *foov1alpha1.ClusterBarList { return &foov1alpha1.ClusterBarList{} },
		),
	}
}
