// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BarSpecApplyConfiguration represents a declarative configuration of the BarSpec type for use
// with apply.
type BarSpecApplyConfiguration struct {
	Message *string `json:"message,omitempty"`
}

// BarSpecApplyConfiguration constructs a declarative configuration of the BarSpec type for use with
// apply.
func BarSpec() *BarSpecApplyConfiguration {
	return &BarSpecApplyConfiguration{}
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *BarSpecApplyConfiguration) WithMessage(value string) *BarSpecApplyConfiguration {
	b.Message = &value
	return b
}
