//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Bar) OpenAPIModelName() string {
	return "cloud.opendefense.foo.v1alpha1.Bar"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BarList) OpenAPIModelName() string {
	return "cloud.opendefense.foo.v1alpha1.BarList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BarSpec) OpenAPIModelName() string {
	return "cloud.opendefense.foo.v1alpha1.BarSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BarStatus) OpenAPIModelName() string {
	return "cloud.opendefense.foo.v1alpha1.BarStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterBar) OpenAPIModelName() string {
	return "cloud.opendefense.foo.v1alpha1.ClusterBar"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterBarList) OpenAPIModelName() string {
	return "cloud.opendefense.foo.v1alpha1.ClusterBarList"
}
