//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Bar{}, func(obj interface{}) { SetObjectDefaults_Bar(obj.(*Bar)) })
	scheme.AddTypeDefaultingFunc(&BarList{}, func(obj interface{}) { SetObjectDefaults_BarList(obj.(*BarList)) })
	scheme.AddTypeDefaultingFunc(&ClusterBar{}, func(obj interface{}) { SetObjectDefaults_ClusterBar(obj.(*ClusterBar)) })
	scheme.AddTypeDefaultingFunc(&ClusterBarList{}, func(obj interface{}) { SetObjectDefaults_ClusterBarList(obj.(*ClusterBarList)) })
	return nil
}

func SetObjectDefaults_Bar(in *Bar) {
	SetDefaults_BarSpec(&in.Spec)
}

func SetObjectDefaults_BarList(in *BarList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Bar(a)
	}
}

func SetObjectDefaults_ClusterBar(in *ClusterBar) {
	SetDefaults_BarSpec(&in.Spec)
}

func SetObjectDefaults_ClusterBarList(in *ClusterBarList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ClusterBar(a)
	}
}
