// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	foov1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BarLister helps list Bars.
// All objects returned here must be treated as read-only.
type BarLister interface {
	// List lists all Bars in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*foov1alpha1.Bar, err error)
	// Bars returns an object that can list and get Bars.
	Bars(namespace string) BarNamespaceLister
	BarListerExpansion
}

// barLister implements the BarLister interface.
type barLister struct {
	listers.ResourceIndexer[*foov1alpha1.Bar]
}

// NewBarLister returns a new BarLister.
func NewBarLister(indexer cache.Indexer) BarLister {
	return &barLister{listers.New[*foov1alpha1.Bar](indexer, foov1alpha1.Resource("bar"))}
}

// Bars returns an object that can list and get Bars.
func (s *barLister) Bars(namespace string) BarNamespaceLister {
	return barNamespaceLister{listers.NewNamespaced[*foov1alpha1.Bar](s.ResourceIndexer, namespace)}
}

// BarNamespaceLister helps list and get Bars.
// All objects returned here must be treated as read-only.
type BarNamespaceLister interface {
	// List lists all Bars in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*foov1alpha1.Bar, err error)
	// Get retrieves the Bar from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*foov1alpha1.Bar, error)
	BarNamespaceListerExpansion
}

// barNamespaceLister implements the BarNamespaceLister
// interface.
type barNamespaceLister struct {
	listers.ResourceIndexer[*foov1alpha1.Bar]
}
