// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	foov1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBarLister helps list ClusterBars.
// All objects returned here must be treated as read-only.
type ClusterBarLister interface {
	// List lists all ClusterBars in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*foov1alpha1.ClusterBar, err error)
	// Get retrieves the ClusterBar from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*foov1alpha1.ClusterBar, error)
	ClusterBarListerExpansion
}

// clusterBarLister implements the ClusterBarLister interface.
type clusterBarLister struct {
	listers.ResourceIndexer[*foov1alpha1.ClusterBar]
}

// NewClusterBarLister returns a new ClusterBarLister.
func NewClusterBarLister(indexer cache.Indexer) ClusterBarLister {
	return &clusterBarLister{listers.New[*foov1alpha1.ClusterBar](indexer, foov1alpha1.Resource("clusterbar"))}
}
