// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BarListerExpansion allows custom methods to be added to
// BarLister.
type BarListerExpansion interface{}

// BarNamespaceListerExpansion allows custom methods to be added to
// BarNamespaceLister.
type BarNamespaceListerExpansion interface{}

// ClusterBarListerExpansion allows custom methods to be added to
// ClusterBarLister.
type ClusterBarListerExpansion interface{}
