// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/kit/example/client-go/clientset/versioned/typed/foo/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFooV1alpha1 struct {
	*testing.Fake
}

func (c *FakeFooV1alpha1) Bars(namespace string) v1alpha1.BarInterface {
	return newFakeBars(c, namespace)
}

func (c *FakeFooV1alpha1) ClusterBars() v1alpha1.ClusterBarInterface {
	return newFakeClusterBars(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFooV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
