// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	foov1alpha1 "go.opendefense.cloud/kit/example/client-go/applyconfigurations/foo/v1alpha1"
	typedfoov1alpha1 "go.opendefense.cloud/kit/example/client-go/clientset/versioned/typed/foo/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterBars implements ClusterBarInterface
type fakeClusterBars struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterBar, *v1alpha1.ClusterBarList, *foov1alpha1.ClusterBarApplyConfiguration]
	Fake *FakeFooV1alpha1
}

func newFakeClusterBars(fake *FakeFooV1alpha1) typedfoov1alpha1.ClusterBarInterface {
	return &fakeClusterBars{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterBar, *v1alpha1.ClusterBarList, *foov1alpha1.ClusterBarApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusterbars"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterBar"),
			func() *v1alpha1.ClusterBar { return &v1alpha1.ClusterBar{} },
			func() *v1alpha1.ClusterBarList { return &v1alpha1.ClusterBarList{} },
			func(dst, src *v1alpha1.ClusterBarList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterBarList) []*v1alpha1.ClusterBar { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ClusterBarList, items []*v1alpha1.ClusterBar) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
