// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/kit/example/api/foo/v1alpha1"
	foov1alpha1 "go.opendefense.cloud/kit/example/client-go/applyconfigurations/foo/v1alpha1"
	typedfoov1alpha1 "go.opendefense.cloud/kit/example/client-go/clientset/versioned/typed/foo/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBars implements BarInterface
type fakeBars struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Bar, *v1alpha1.BarList, *foov1alpha1.BarApplyConfiguration]
	Fake *FakeFooV1alpha1
}

func newFakeBars(fake *FakeFooV1alpha1, namespace string) typedfoov1alpha1.BarInterface {
	return &fakeBars{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Bar, *v1alpha1.BarList, *foov1alpha1.BarApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("bars"),
			v1alpha1.SchemeGroupVersion.WithKind("Bar"),
			func() *v1alpha1.Bar { return &v1alpha1.Bar{} },
			func() *v1alpha1.BarList { return &v1alpha1.BarList{} },
			func(dst, src *v1alpha1.BarList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BarList) []*v1alpha1.Bar { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.BarList, items []*v1alpha1.Bar) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
