name: Codegen Check
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - id: go-version
        uses: opendefensecloud/dev-kit/.github/actions/get-go-version@41370fd52f6889401ef79388e54e7e38bfbf112e # v1.0.11
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - name: Run codegen
        run: |
          cd example && make codegen
      - name: Check for changes
        uses: opendefensecloud/dev-kit/.github/actions/diff-check@41370fd52f6889401ef79388e54e7e38bfbf112e # v1.0.11
